AdministrativoImperial/Controllers/LoginController.cs
using AdministrativoImperial.Domain.IBusiness;
using AdministrativoImperial.Domain.Models.Body;
using AdministrativoImperial.Domain.Models.EntityDomain;
using Gpnet.Common.ExecutionManager;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using @BCryptNet = BCrypt.Net;

namespace AdministrativoImperial.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioBusiness _usuarioBusiness;

        public LoginController(IUsuarioBusiness usuarioBusiness)
        {
            _usuarioBusiness = usuarioBusiness;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> Autenticar([FromBody] UsuarioBody usuario)
        {
            if (ModelState.IsValid)
            {
                var resultUsuario = await _usuarioBusiness.SelecionarPorEmail(usuario.email);
                if (resultUsuario.Type != ResultType.CompleteExecution)
                    return Json(new { erro = true, mensagem = resultUsuario.Messages });

                if (resultUsuario.Item != null)
                {
                    var hashSenhaArmazenada = Encoding.UTF8.GetString(resultUsuario.Item.UsaSenha);
                    var saltString = Encoding.UTF8.GetString(resultUsuario.Item.UsaSalt);
                    var hashSenhaAtual = BCryptNet.BCrypt.HashPassword(usuario.senha, saltString);

                    if (!hashSenhaAtual.Equals(hashSenhaArmazenada))
                        return Json(new { erro = true, mensagem = "Senha inválida. Verifique e tente novamente!" });

                    HttpContext.Session.SetInt32("__Autenticado", 1);
                    HttpContext.Session.SetString("__Usuario", resultUsuario.Item.UsaNome);

                    return Json(new { erro = false, mensagem = "Usuário autenticado!", infoUser = new { resultUsuario.Item.UsaId, resultUsuario.Item.UsaNome } } );
                }
                else
                    return Json(new { erro = true, mensagem = "Email não encontrado. Verifique e tente novamente!" });
            }
            else
            {
                var erros = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                return Json(new { erro = true, mensagem = erros });
            }

        }

    }
}

AdministrativoImperial/Controllers/MaterialController.cs
using AdministrativoImperial.Domain.IBusiness;
using AdministrativoImperial.Domain.Models.Common;
using AdministrativoImperial.Domain.Models.EntityDomain;
using AdministrativoImperial.Models;
using Gpnet.Common.ExecutionManager;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AdministrativoImperial.Controllers
{
    public class MaterialController : Controller
    {
        private readonly IMaterialBusiness _materialBusiness;
        private readonly IObraBusiness _obraBusiness;

        public MaterialController(IMaterialBusiness materialBusiness, IObraBusiness obraBusiness)
        {
            _materialBusiness = materialBusiness;
            _obraBusiness = obraBusiness;
        }

        public IActionResult Index()
        {
            ViewBag.Titulo = "Lista de Materiais";
            ViewBag.ListaObras = _obraBusiness.ObterCadastrados().Result.Items;
            return View();
        }

        #region Writer

        [HttpPost]
        [Route("[controller]/[action]")]
        public async Task<JsonResult> Cadastrar([FromBody] MaterialDTO model)
        {
            if (ModelState.IsValid)
            {
                var resultado = await _materialBusiness.Create(model);

                if (resultado.Type != ResultType.CompleteExecution)
                    return Json(new { erro = true, mensagem = resultado.Messages });

                return Json(new { erro = false, mensagem = resultado.Messages });
            }
            else
            {
                var erros = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                return Json(new { erro = true, mensagem = erros });
            }

        }

        [HttpGet]
        [Route("[controller]/[action]/{id:int}")]
        public async Task<JsonResult> Deletar(int id)
        {
            var resultado = await _materialBusiness.Deletar(id);

            if (resultado.Type != ResultType.CompleteExecution)
                return Json(new { erro = true, mensagem = resultado.Messages });

            return Json(new { erro = false, mensagem = resultado.Messages });
        }

        #endregion

        #region Read


        [HttpGet]
        public async Task<ViewResult> Listar()
        {
            var result = await _materialBusiness.GetAllAsync();
            return View("Listar", result.Items);
        }

        [HttpGet]
        [Route("[controller]/[action]/{mtrId:int}")]
        public async Task<JsonResult> Selecionar(int mtrId)
        {
            var result = await _materialBusiness.Selecionar(mtrId);
            return Json(new { result.Item });
        }

        #endregion

    }
}

AdministrativoImperial/Controllers/ObraController.cs
using AdministrativoImperial.Domain.IBusiness;
using AdministrativoImperial.Domain.Models.EntityDomain;
using Gpnet.Common.ExecutionManager;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AdministrativoImperial.Controllers
{
	public class ObraController : Controller
    {
        private readonly IObraBusiness _obraBusiness;

        public ObraController(IObraBusiness obraBusiness)
        {
            _obraBusiness = obraBusiness;
        }

        public IActionResult Index()
        {
			return View();
		}

		#region Write

		[HttpPost]
        [Route("[controller]/[action]")]
        public async Task<JsonResult> Cadastrar([FromBody] ObraDTO obra)
        {
            var result = await _obraBusiness.Cadastrar(obra);

            if (result.Type != ResultType.CompleteExecution)
                return Json(new { erro = true, mensagem = result.Messages }) ;

            return Json(new { erro = false, mensagem = result.Messages });
        }

        [HttpGet]
        [Route("[controller]/[action]/{obrId:int}")]
        public async Task<JsonResult> Deletar(int obrId)
        {
            var result = await _obraBusiness.Deletar(obrId);
            if(result.Type != ResultType.CompleteExecution)
                return Json(new { erro = true, mensagem = result.Messages });

            return Json(new { erro = false, mensagem = result.Messages });
        }

        #endregion

        #region Read

        [Route("[controller]/[action]")]
        public async Task<ViewResult> Listar()
        {
            var result = await _obraBusiness.ObterCadastrados();
            return View("Listar", result.Items);
        }

        [HttpGet]
        [Route("[controller]/[action]")]
        public async Task<JsonResult> ObterTodasObras()
        {
            var resultado = await _obraBusiness.ObterCadastrados();
            return Json(new { resultado });
        }

        [HttpGet]
        [Route("[controller]/[action]/{obrId:int}")]
        public async Task<JsonResult> Selecionar(int obrId)
        {
            var result = await _obraBusiness.Selecionar(obrId);
            return Json(new { data = result.Item });
        }

        #endregion
    }
}

AdministrativoImperial/Controllers/UsuarioController.cs
using AdministrativoImperial.Domain.IBusiness;
using AdministrativoImperial.Domain.Models.EntityDomain;
using Gpnet.Common.ExecutionManager;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using @BCryptNet = BCrypt.Net;

namespace AdministrativoImperial.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioBusiness _usuarioBusiness;

        public UsuarioController(IUsuarioBusiness usuarioBusiness)
        {
            _usuarioBusiness = usuarioBusiness;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Write

        [HttpPost]
        [Route("[controller]/[action]")]
        public async Task<JsonResult> Cadastrar([FromBody] UsuarioDTO usuario)
        {
            if (ModelState.IsValid)
            {
                var resultado = await _usuarioBusiness.Cadastrar(usuario);

                if (resultado.Type != ResultType.CompleteExecution)
                    return Json(new { erro = true, mensagem = resultado.Messages });

                return Json(new { erro = false, mensagem = resultado.Messages });
            }
            else
            {
                var erros = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                return Json(new { erro = true, mensagem = erros });
            }

        }

        [HttpGet]
        [Route("[controller]/[action]/{usaId:int}")]
        public async Task<JsonResult> Deletar(int usaId)
        {
            var result = await _usuarioBusiness.Deletar(usaId);
            if (result.Type != ResultType.CompleteExecution)
                return Json(new { erro = true, mensagem = result.Messages });

            return Json(new { erro = false, mensagem = result.Messages });
        }

        #endregion

        #region Read

        [HttpGet]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> Listar()
        {
            var resultado = await _usuarioBusiness.Listar();
            return View("Listar", resultado.Items);
        }

        [HttpGet]
        [Route("[controller]/[action]/{usaId:int}")]
        public async Task<JsonResult> Selecionar(int usaId)
        {
            var result = await _usuarioBusiness.Selecionar(usaId);
            if(result.Type != ResultType.CompleteExecution)
                return Json(new { erro = true, mensagem = result.Messages });

            return Json(new { erro = false, mensagem = result.Messages, data = result.Item });
        }

        #endregion

    }
}

AdministrativoImperial/Views/Shared/ErrorAuthentication.cshtml
@{
	ViewData["Title"] = "Error";
	Layout = "";
}
<head>
    <style>
		 html, body {
			 margin: 0;
			 height: 100vh;
			 font-family: 'Chicle', cursive;
		}
		 body {
			background: url(https://localhost:44391/img/police.png);
			 background-size: cover;
			 background-position: 50% 50%;
			 display: flex;
			 justify-content: center;
			 align-items: center;
		}
		 .container {
			 background: rgba(255,255,255,0.8);
			 padding: 1em 2em;
			 font-size: 1.5em;
			 text-align: center;
			 margin-top: 30vh;
		}
		 h1 {
			 color: #e60000;
		}
    </style>
</head>

<div class="container">
    <h1>Desculpe pessoal, mas essa pagina não é permetida.</h1>
    <p>Faça o login para ter acesso</p>
	<a asp-controller="Login" asp-action="Index">Voltar para Login</a>
</div>

AdministrativoImperial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/img/logo-sem-fundo.png">
    <title>@ViewData["Title"] - Administrativo Imperial</title>

    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

    <!-- Nucleo Icons -->
    <link href="~/criativeTim/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/criativeTim/css/nucleo-svg.css" rel="stylesheet" />

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    <!-- Notifications -->
    <link href="~/lib/sh-toastr-master/css/sh_toaster.css" rel="stylesheet" />

    <!-- CSS Files -->
    <link id="pagestyle" href="~/criativeTim/css/argon-dashboard.css?v=2.0.2" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site_layout_menu.css" />

    <!-- JS Script -->
    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>

</head>

<body class="g-sidenav-show bg-gray-100">
    <div id="loader">
        <div class="spinner-grow text-light" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <div id="notificacoes">
        <div class="sh-toast-container" id="shToastContainerTop"></div>
        <div class="sh-toast-container" id="shToastContainerBottom"></div>
    </div>
    <div class="min-height-300 bg-primary position-absolute w-100"></div>

    <div class='dashboard'>
        <div class="dashboard-nav bg-primary">
            <header>
                <a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a><a href="#" class="brand-logo">
                    <span>Imperial</span>
                </a>
            </header>
            <nav class="dashboard-nav-list">
                @* <a asp-controller="Dashboard" asp-action="Index" class="dashboard-nav-item active"><i class="fa fa-bar-chart"></i>Dashboard</a> *@
                <a asp-controller="Obra" asp-action="Index" class="dashboard-nav-item"><i class="fa-solid fa-person-digging"></i> Obra</a>

                @* <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                        <i class="fa fa-money"></i> Receita
                    </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a href="#"
                           class="dashboard-nav-dropdown-item">All</a><a href="#" class="dashboard-nav-dropdown-item">Recent</a><a href="#" class="dashboard-nav-dropdown-item">Images</a><a href="#" class="dashboard-nav-dropdown-item">Video</a> 
                    </div>
                </div> *@
                <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                        <i class="fa fa-credit-card"></i> Despesas
                    </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a asp-controller="DiasTrabalhados" asp-action="Index" class="dashboard-nav-dropdown-item">Dias trabalhados</a>
                        @* <a asp-controller="Material" asp-action="Index" class="dashboard-nav-dropdown-item">Materiais</a> *@
                    </div>
                </div>

                <a asp-controller="Funcionario" asp-action="Index" class="dashboard-nav-item"><i class="fa fa-users"></i> Funcionários </a>
                <a asp-controller="FuncaoFuncionario" asp-action="Index" class="dashboard-nav-item"><i class="fas fa-cogs"></i> Função Funcionários </a>
                @* <a asp-controller="Usuario" asp-action="Index" class="dashboard-nav-item"><i class="fa-solid fa-users-gear"></i> Usuários </a> *@
                <div class="nav-item-divider"></div>
                @* <a href="#" class="dashboard-nav-item" onclick="MensagemAvisoManutenção()"><i class="fas fa-user"></i> Perfil </a> *@
                <a asp-controller="Login" asp-action="Index" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Logout </a>
            </nav>
        </div>
        <div class='dashboard-app'>
            <header class='dashboard-toolbar bg-primary'><a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a></header>
            <div class='dashboard-content'>

                <main role="main" class="main-content position-relative border-radius-lg ps">
                    @RenderBody()

                    <footer class="border-top footer text-muted mt-5">
                        <div class="dashboard-content">
                            &copy; 2024 - AdministrativoImperial
                        </div>
                    </footer>
                </main>

            </div>
        </div>
    </div>

    <!--   JS Files Criative Tim   -->
    <script src="~/criativeTim/js/core/popper.min.js"></script>
    <script src="~/criativeTim/js/core/bootstrap.min.js"></script>
    <script src="~/criativeTim/js/plugin/perfect-scrollbar.min.js"></script>
    <script src="~/criativeTim/js/plugin/smooth-scrollbar.min.js"></script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="~/criativeTim/js/argon-dashboard.min.js?v=2.0.2"></script>

    <!--  JS Files   -->
    <script src="~/js/jquery.mask.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site_layout_menu.js" asp-append-version="true"></script>
    <script src="~/js/utilities.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js" asp-append-version="true"></script>
    <script src="~/lib/sh-toastr-master/js/sh_toaster.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>